In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/insurance.csv')
df.head()

,Id,age,gender,bmi,bloodpressure,diabetic,children,smoker,region,claim
0,1,39.0,male,23.2,91,Yes,0,No,southeast,1121.87
1,2,24.0,male,30.1,87,No,0,No,southeast,1131.51
2,3,NaN,male,33.3,82,Yes,0,No,southeast,1135.94
3,4,NaN,male,33.7,80,No,0,No,northwest,1136.40
4,5,NaN,male,34.1,100,No,0,No,northwest,1137.01

In [3]:
df.shape

(1340, 10)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1340 non-null   int64
 1   age            1335 non-null   float64
 2   gender         1340 non-null   str
 3   bmi            1340 non-null   float64
 4   bloodpressure  1340 non-null   int64
 5   diabetic       1340 non-null   str
 6   children       1340 non-null   int64
 7   smoker         1340 non-null   str
 8   region         1337 non-null   str
 9   claim          1340 non-null   float64
dtypes: float64(3), int64(3), str(4)
memory usage: 104.8 KB

In [5]:
df.describe()

,Id,age,bmi,bloodpressure,children,claim
count,1340.000000,1335.000000,1340.000000,1340.000000,1340.000000,1340.000000
mean,670.500000,38.078652,30.668955,94.157463,1.093284,13252.745642
std,386.968991,11.102924,6.106735,11.434712,1.205334,12109.609288
min,1.000000,18.000000,16.000000,80.000000,0.000000,1121.870000
25%,335.750000,29.000000,26.275000,86.000000,0.000000,4719.685000
50%,670.500000,38.000000,30.400000,92.000000,1.000000,9369.615000
75%,1005.250000,47.000000,34.700000,99.000000,2.000000,16604.305000
max,1340.000000,60.000000,53.100000,140.000000,5.000000,63770.430000

In [6]:
df.isna().sum()

Id               0
age              5
gender           0
bmi              0
bloodpressure    0
diabetic         0
children         0
smoker           0
region           3
claim            0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

# Split into train & test :

In [8]:
X = df.drop(["claim", "Id"], axis=1)
y = df["claim"]

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# imputation :

In [10]:
X_train.isna().sum()

age              5
gender           0
bmi              0
bloodpressure    0
diabetic         0
children         0
smoker           0
region           3
dtype: int64

In [11]:
X_train["age"] = X_train["age"].fillna(X_train["age"].mean())
X_test["age"] = X_test["age"].fillna(X_train["age"].mean())


X_train["region"] = X_train["region"].fillna(X_train["region"].mode()[0])
X_test["region"] = X_test["region"].fillna(X_train["region"].mode()[0])

In [12]:
X_train.isna().sum()

age              0
gender           0
bmi              0
bloodpressure    0
diabetic         0
children         0
smoker           0
region           0
dtype: int64

In [13]:
X_train.head(10)

       age  gender   bmi  bloodpressure diabetic  children smoker     region
1177  55.0  female  27.7            111      Yes         0    Yes  northeast
1080  43.0    male  33.0             85       No         0     No  southeast
332   46.0  female  28.6             80       No         5     No  southwest
355   38.0    male  30.1             87       No         5     No  southeast
138   32.0    male  24.5             90      Yes         0     No  southeast
381   44.0  female  25.8             90       No         0     No  northwest
292   21.0    male  35.8             88       No         0     No  northwest
1091  22.0    male  28.1             95      Yes         4    Yes  northwest
479   35.0    male  16.8             98       No         2     No  southeast
141   46.0    male  50.4             89      Yes         1     No  southeast

# Scaling :

In [14]:
num_train = X_train.select_dtypes("number")
num_test = X_test.select_dtypes("number")

In [15]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaled_num_train = scaler.fit_transform(num_train)
scaled_num_test = scaler.transform(num_test)

In [16]:
num_train = pd.DataFrame(scaled_num_train, columns=num_train.columns)
num_test = pd.DataFrame(scaled_num_test, columns=num_test.columns)

In [17]:
num_train

          age       bmi  bloodpressure  children
0    1.515835 -0.472091       1.435636 -0.888299
1    0.438840  0.397248      -0.808022 -0.888299
2    0.708088 -0.324468      -1.239495  3.244759
3   -0.009908 -0.078428      -0.635433  3.244759
4   -0.548405 -0.996975      -0.376550 -0.888299
..        ...       ...            ...       ...
933 -0.009908 -0.865754       0.831574 -0.061687
934  0.079842 -0.488494       0.831574 -0.061687
935 -0.189407 -0.062026       3.075232 -0.061687
936 -0.099658  0.462858      -0.894317 -0.888299
937  1.156836  1.857081       1.004163 -0.888299

[938 rows x 4 columns]

# Encoding :

In [18]:
cat_train = X_train.select_dtypes("object")
cat_test = X_test.select_dtypes("object")

C:\Users\sol\AppData\Local\Temp\ipykernel_14616\1148509511.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_train = X_train.select_dtypes("object")
C:\Users\sol\AppData\Local\Temp\ipykernel_14616\1148509511.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_test = X_test.select_dtypes("object")

In [19]:
cat_train = pd.get_dummies(cat_train, drop_first=True)
cat_test = pd.get_dummies(cat_test, drop_first=True)
cat_test = cat_test.reindex(columns=cat_train.columns, fill_value=0)

In [20]:
cat_train

,gender_male,diabetic_Yes,smoker_Yes,region_northwest,region_southeast,region_southwest
1177,False,True,True,False,False,False
1080,True,False,False,False,True,False
332,False,False,False,False,False,True
355,True,False,False,False,True,False
138,True,True,False,False,True,False
...,...,...,...,...,...,...
1095,False,True,True,False,False,False
1130,False,True,True,False,False,True
1294,False,False,True,True,False,False
860,False,True,False,True,False,False
1126,False,False,False,False,True,False

# concat numerical and categorical data :

In [21]:
num_train = num_train.reset_index(drop=True)   # **i have to reset their indexes, because if i don't it will concat by index, so it causes missing values after concatenation !!!**
cat_train = cat_train.reset_index(drop=True)

num_test = num_test.reset_index(drop=True)
cat_test = cat_test.reset_index(drop=True)

In [22]:
new_X_train = pd.concat([num_train, cat_train], axis=1)
new_X_test = pd.concat([num_test, cat_test], axis=1)

X_train = new_X_train.copy()
X_test = new_X_test.copy()

In [23]:
new_X_train

,age,bmi,bloodpressure,children,gender_male,diabetic_Yes,smoker_Yes,region_northwest,region_southeast,region_southwest
0,1.515835,-0.472091,1.435636,-0.888299,False,True,True,False,False,False
1,0.438840,0.397248,-0.808022,-0.888299,True,False,False,False,True,False
2,0.708088,-0.324468,-1.239495,3.244759,False,False,False,False,False,True
3,-0.009908,-0.078428,-0.635433,3.244759,True,False,False,False,True,False
4,-0.548405,-0.996975,-0.376550,-0.888299,True,True,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...
933,-0.009908,-0.865754,0.831574,-0.061687,False,True,True,False,False,False
934,0.079842,-0.488494,0.831574,-0.061687,False,True,True,False,False,True
935,-0.189407,-0.062026,3.075232,-0.061687,False,False,True,True,False,False
936,-0.099658,0.462858,-0.894317,-0.888299,False,True,False,True,False,False
937,1.156836,1.857081,1.004163,-0.888299,False,False,False,False,True,False

In [24]:
X_train = new_X_train.copy()
X_test = new_X_test.copy()

# training & Evaluation :

## Linear Regression :

In [25]:
from sklearn.linear_model import LinearRegression

lr_model = LinearRegression()

lr_model.fit(X_train, y_train)

y_pred = lr_model.predict(X_test)

In [26]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"mse : {mse} \n r2 : {r2}")

mse : 42562665.81044649
 r2 : 0.7325542179823428

## Polynomial Features :

In [49]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

pf_model = LinearRegression()
poly = PolynomialFeatures(degree=2)
poly_X_train = poly.fit_transform(X_train)

pf_model.fit(poly_X_train, y_train)

y_pred = pf_model.predict(poly.transform(X_test))

In [51]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"mse : {mse} \n r2 : {r2}")

mse : 32815675.577259615
 r2 : 0.7938001802733919

## Random Forest :

In [27]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor()

rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

In [28]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"mse : {mse} \n r2 : {r2}")

mse : 29299188.27193191
 r2 : 0.8158962985362124

# Hyperparameters tuning :

In [29]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    random_state=42
)

params = {
    "n_estimators": [100, 200, 300],
    "max_depth": [3, 5, 10, 15, 20, None],
    "min_samples_split": [2, 5, 10, 20],
    "min_samples_leaf": [1, 2, 5, 10],
    "max_features": [0.5, 0.7, 1.0]
}

search = RandomizedSearchCV(
    rf,
    params,
    n_iter=20,
    cv=5,
    scoring="r2",
    random_state=42,
    n_jobs=-1
)

search.fit(X_train, y_train)

print(search.best_params_)
print(search.best_score_)

{'n_estimators': 300, 'min_samples_split': 20, 'min_samples_leaf': 1, 'max_features': 0.7, 'max_depth': 20}
0.7904742244775523

In [30]:
best_rf = search.best_estimator_

y_pred = best_rf.predict(X_test)

print(r2_score(y_test, y_pred))

0.8396635512481925